name: Build & Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go 1.23.4
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Linter
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      - name: Build Project
        run: go build -v ./...

      - name: Run Tests with Coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v4
        with:
          file: coverage.out
          flags: unittests
          name: go-code-coverage
          fail_ci_if_error: true
